// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic.proto

package traffic;

public final class Traffic {
  private Traffic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrafficCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:traffic.TrafficCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string intersectionId = 1;</code>
     */
    java.lang.String getIntersectionId();
    /**
     * <code>string intersectionId = 1;</code>
     */
    com.google.protobuf.ByteString
        getIntersectionIdBytes();

    /**
     * <code>.traffic.TrafficCommand.Command command = 2;</code>
     */
    int getCommandValue();
    /**
     * <code>.traffic.TrafficCommand.Command command = 2;</code>
     */
    traffic.Traffic.TrafficCommand.Command getCommand();
  }
  /**
   * <pre>
   * Define the request message for traffic command
   * </pre>
   *
   * Protobuf type {@code traffic.TrafficCommand}
   */
  public  static final class TrafficCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:traffic.TrafficCommand)
      TrafficCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrafficCommand.newBuilder() to construct.
    private TrafficCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrafficCommand() {
      intersectionId_ = "";
      command_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrafficCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              intersectionId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              command_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return traffic.Traffic.internal_static_traffic_TrafficCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return traffic.Traffic.internal_static_traffic_TrafficCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              traffic.Traffic.TrafficCommand.class, traffic.Traffic.TrafficCommand.Builder.class);
    }

    /**
     * <pre>
     * Enum for command types including the END_STREAM command
     * </pre>
     *
     * Protobuf enum {@code traffic.TrafficCommand.Command}
     */
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TURN_GREEN = 0;</code>
       */
      TURN_GREEN(0),
      /**
       * <code>TURN_RED = 1;</code>
       */
      TURN_RED(1),
      /**
       * <pre>
       * Added the END_STREAM command
       * </pre>
       *
       * <code>END_STREAM = 2;</code>
       */
      END_STREAM(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TURN_GREEN = 0;</code>
       */
      public static final int TURN_GREEN_VALUE = 0;
      /**
       * <code>TURN_RED = 1;</code>
       */
      public static final int TURN_RED_VALUE = 1;
      /**
       * <pre>
       * Added the END_STREAM command
       * </pre>
       *
       * <code>END_STREAM = 2;</code>
       */
      public static final int END_STREAM_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Command valueOf(int value) {
        return forNumber(value);
      }

      public static Command forNumber(int value) {
        switch (value) {
          case 0: return TURN_GREEN;
          case 1: return TURN_RED;
          case 2: return END_STREAM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Command> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return traffic.Traffic.TrafficCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final Command[] VALUES = values();

      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Command(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:traffic.TrafficCommand.Command)
    }

    public static final int INTERSECTIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object intersectionId_;
    /**
     * <code>string intersectionId = 1;</code>
     */
    public java.lang.String getIntersectionId() {
      java.lang.Object ref = intersectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        intersectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string intersectionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIntersectionIdBytes() {
      java.lang.Object ref = intersectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        intersectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_FIELD_NUMBER = 2;
    private int command_;
    /**
     * <code>.traffic.TrafficCommand.Command command = 2;</code>
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.traffic.TrafficCommand.Command command = 2;</code>
     */
    public traffic.Traffic.TrafficCommand.Command getCommand() {
      @SuppressWarnings("deprecation")
      traffic.Traffic.TrafficCommand.Command result = traffic.Traffic.TrafficCommand.Command.valueOf(command_);
      return result == null ? traffic.Traffic.TrafficCommand.Command.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIntersectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, intersectionId_);
      }
      if (command_ != traffic.Traffic.TrafficCommand.Command.TURN_GREEN.getNumber()) {
        output.writeEnum(2, command_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIntersectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, intersectionId_);
      }
      if (command_ != traffic.Traffic.TrafficCommand.Command.TURN_GREEN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, command_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof traffic.Traffic.TrafficCommand)) {
        return super.equals(obj);
      }
      traffic.Traffic.TrafficCommand other = (traffic.Traffic.TrafficCommand) obj;

      boolean result = true;
      result = result && getIntersectionId()
          .equals(other.getIntersectionId());
      result = result && command_ == other.command_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERSECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getIntersectionId().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + command_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static traffic.Traffic.TrafficCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static traffic.Traffic.TrafficCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static traffic.Traffic.TrafficCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static traffic.Traffic.TrafficCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(traffic.Traffic.TrafficCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the request message for traffic command
     * </pre>
     *
     * Protobuf type {@code traffic.TrafficCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:traffic.TrafficCommand)
        traffic.Traffic.TrafficCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return traffic.Traffic.internal_static_traffic_TrafficCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return traffic.Traffic.internal_static_traffic_TrafficCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                traffic.Traffic.TrafficCommand.class, traffic.Traffic.TrafficCommand.Builder.class);
      }

      // Construct using traffic.Traffic.TrafficCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        intersectionId_ = "";

        command_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return traffic.Traffic.internal_static_traffic_TrafficCommand_descriptor;
      }

      @java.lang.Override
      public traffic.Traffic.TrafficCommand getDefaultInstanceForType() {
        return traffic.Traffic.TrafficCommand.getDefaultInstance();
      }

      @java.lang.Override
      public traffic.Traffic.TrafficCommand build() {
        traffic.Traffic.TrafficCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public traffic.Traffic.TrafficCommand buildPartial() {
        traffic.Traffic.TrafficCommand result = new traffic.Traffic.TrafficCommand(this);
        result.intersectionId_ = intersectionId_;
        result.command_ = command_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof traffic.Traffic.TrafficCommand) {
          return mergeFrom((traffic.Traffic.TrafficCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(traffic.Traffic.TrafficCommand other) {
        if (other == traffic.Traffic.TrafficCommand.getDefaultInstance()) return this;
        if (!other.getIntersectionId().isEmpty()) {
          intersectionId_ = other.intersectionId_;
          onChanged();
        }
        if (other.command_ != 0) {
          setCommandValue(other.getCommandValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        traffic.Traffic.TrafficCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (traffic.Traffic.TrafficCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object intersectionId_ = "";
      /**
       * <code>string intersectionId = 1;</code>
       */
      public java.lang.String getIntersectionId() {
        java.lang.Object ref = intersectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          intersectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIntersectionIdBytes() {
        java.lang.Object ref = intersectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          intersectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public Builder setIntersectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        intersectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public Builder clearIntersectionId() {
        
        intersectionId_ = getDefaultInstance().getIntersectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public Builder setIntersectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        intersectionId_ = value;
        onChanged();
        return this;
      }

      private int command_ = 0;
      /**
       * <code>.traffic.TrafficCommand.Command command = 2;</code>
       */
      public int getCommandValue() {
        return command_;
      }
      /**
       * <code>.traffic.TrafficCommand.Command command = 2;</code>
       */
      public Builder setCommandValue(int value) {
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.traffic.TrafficCommand.Command command = 2;</code>
       */
      public traffic.Traffic.TrafficCommand.Command getCommand() {
        @SuppressWarnings("deprecation")
        traffic.Traffic.TrafficCommand.Command result = traffic.Traffic.TrafficCommand.Command.valueOf(command_);
        return result == null ? traffic.Traffic.TrafficCommand.Command.UNRECOGNIZED : result;
      }
      /**
       * <code>.traffic.TrafficCommand.Command command = 2;</code>
       */
      public Builder setCommand(traffic.Traffic.TrafficCommand.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.traffic.TrafficCommand.Command command = 2;</code>
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:traffic.TrafficCommand)
    }

    // @@protoc_insertion_point(class_scope:traffic.TrafficCommand)
    private static final traffic.Traffic.TrafficCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new traffic.Traffic.TrafficCommand();
    }

    public static traffic.Traffic.TrafficCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrafficCommand>
        PARSER = new com.google.protobuf.AbstractParser<TrafficCommand>() {
      @java.lang.Override
      public TrafficCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrafficCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrafficCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrafficCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public traffic.Traffic.TrafficCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrafficStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:traffic.TrafficState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string intersectionId = 1;</code>
     */
    java.lang.String getIntersectionId();
    /**
     * <code>string intersectionId = 1;</code>
     */
    com.google.protobuf.ByteString
        getIntersectionIdBytes();

    /**
     * <code>.traffic.TrafficState.State currentState = 2;</code>
     */
    int getCurrentStateValue();
    /**
     * <code>.traffic.TrafficState.State currentState = 2;</code>
     */
    traffic.Traffic.TrafficState.State getCurrentState();
  }
  /**
   * <pre>
   * Define the response message for traffic state
   * </pre>
   *
   * Protobuf type {@code traffic.TrafficState}
   */
  public  static final class TrafficState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:traffic.TrafficState)
      TrafficStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrafficState.newBuilder() to construct.
    private TrafficState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrafficState() {
      intersectionId_ = "";
      currentState_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrafficState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              intersectionId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              currentState_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return traffic.Traffic.internal_static_traffic_TrafficState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return traffic.Traffic.internal_static_traffic_TrafficState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              traffic.Traffic.TrafficState.class, traffic.Traffic.TrafficState.Builder.class);
    }

    /**
     * <pre>
     * Enum for state types including an UNKNOWN state
     * </pre>
     *
     * Protobuf enum {@code traffic.TrafficState.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GREEN = 0;</code>
       */
      GREEN(0),
      /**
       * <code>RED = 1;</code>
       */
      RED(1),
      /**
       * <pre>
       * Added the UNKNOWN state for undefined or error states
       * </pre>
       *
       * <code>UNKNOWN = 2;</code>
       */
      UNKNOWN(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GREEN = 0;</code>
       */
      public static final int GREEN_VALUE = 0;
      /**
       * <code>RED = 1;</code>
       */
      public static final int RED_VALUE = 1;
      /**
       * <pre>
       * Added the UNKNOWN state for undefined or error states
       * </pre>
       *
       * <code>UNKNOWN = 2;</code>
       */
      public static final int UNKNOWN_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      public static State forNumber(int value) {
        switch (value) {
          case 0: return GREEN;
          case 1: return RED;
          case 2: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return traffic.Traffic.TrafficState.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:traffic.TrafficState.State)
    }

    public static final int INTERSECTIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object intersectionId_;
    /**
     * <code>string intersectionId = 1;</code>
     */
    public java.lang.String getIntersectionId() {
      java.lang.Object ref = intersectionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        intersectionId_ = s;
        return s;
      }
    }
    /**
     * <code>string intersectionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIntersectionIdBytes() {
      java.lang.Object ref = intersectionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        intersectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTSTATE_FIELD_NUMBER = 2;
    private int currentState_;
    /**
     * <code>.traffic.TrafficState.State currentState = 2;</code>
     */
    public int getCurrentStateValue() {
      return currentState_;
    }
    /**
     * <code>.traffic.TrafficState.State currentState = 2;</code>
     */
    public traffic.Traffic.TrafficState.State getCurrentState() {
      @SuppressWarnings("deprecation")
      traffic.Traffic.TrafficState.State result = traffic.Traffic.TrafficState.State.valueOf(currentState_);
      return result == null ? traffic.Traffic.TrafficState.State.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIntersectionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, intersectionId_);
      }
      if (currentState_ != traffic.Traffic.TrafficState.State.GREEN.getNumber()) {
        output.writeEnum(2, currentState_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIntersectionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, intersectionId_);
      }
      if (currentState_ != traffic.Traffic.TrafficState.State.GREEN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, currentState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof traffic.Traffic.TrafficState)) {
        return super.equals(obj);
      }
      traffic.Traffic.TrafficState other = (traffic.Traffic.TrafficState) obj;

      boolean result = true;
      result = result && getIntersectionId()
          .equals(other.getIntersectionId());
      result = result && currentState_ == other.currentState_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTERSECTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getIntersectionId().hashCode();
      hash = (37 * hash) + CURRENTSTATE_FIELD_NUMBER;
      hash = (53 * hash) + currentState_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static traffic.Traffic.TrafficState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static traffic.Traffic.TrafficState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static traffic.Traffic.TrafficState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static traffic.Traffic.TrafficState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static traffic.Traffic.TrafficState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static traffic.Traffic.TrafficState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static traffic.Traffic.TrafficState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static traffic.Traffic.TrafficState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static traffic.Traffic.TrafficState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static traffic.Traffic.TrafficState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static traffic.Traffic.TrafficState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static traffic.Traffic.TrafficState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(traffic.Traffic.TrafficState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the response message for traffic state
     * </pre>
     *
     * Protobuf type {@code traffic.TrafficState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:traffic.TrafficState)
        traffic.Traffic.TrafficStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return traffic.Traffic.internal_static_traffic_TrafficState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return traffic.Traffic.internal_static_traffic_TrafficState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                traffic.Traffic.TrafficState.class, traffic.Traffic.TrafficState.Builder.class);
      }

      // Construct using traffic.Traffic.TrafficState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        intersectionId_ = "";

        currentState_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return traffic.Traffic.internal_static_traffic_TrafficState_descriptor;
      }

      @java.lang.Override
      public traffic.Traffic.TrafficState getDefaultInstanceForType() {
        return traffic.Traffic.TrafficState.getDefaultInstance();
      }

      @java.lang.Override
      public traffic.Traffic.TrafficState build() {
        traffic.Traffic.TrafficState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public traffic.Traffic.TrafficState buildPartial() {
        traffic.Traffic.TrafficState result = new traffic.Traffic.TrafficState(this);
        result.intersectionId_ = intersectionId_;
        result.currentState_ = currentState_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof traffic.Traffic.TrafficState) {
          return mergeFrom((traffic.Traffic.TrafficState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(traffic.Traffic.TrafficState other) {
        if (other == traffic.Traffic.TrafficState.getDefaultInstance()) return this;
        if (!other.getIntersectionId().isEmpty()) {
          intersectionId_ = other.intersectionId_;
          onChanged();
        }
        if (other.currentState_ != 0) {
          setCurrentStateValue(other.getCurrentStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        traffic.Traffic.TrafficState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (traffic.Traffic.TrafficState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object intersectionId_ = "";
      /**
       * <code>string intersectionId = 1;</code>
       */
      public java.lang.String getIntersectionId() {
        java.lang.Object ref = intersectionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          intersectionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIntersectionIdBytes() {
        java.lang.Object ref = intersectionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          intersectionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public Builder setIntersectionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        intersectionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public Builder clearIntersectionId() {
        
        intersectionId_ = getDefaultInstance().getIntersectionId();
        onChanged();
        return this;
      }
      /**
       * <code>string intersectionId = 1;</code>
       */
      public Builder setIntersectionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        intersectionId_ = value;
        onChanged();
        return this;
      }

      private int currentState_ = 0;
      /**
       * <code>.traffic.TrafficState.State currentState = 2;</code>
       */
      public int getCurrentStateValue() {
        return currentState_;
      }
      /**
       * <code>.traffic.TrafficState.State currentState = 2;</code>
       */
      public Builder setCurrentStateValue(int value) {
        currentState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.traffic.TrafficState.State currentState = 2;</code>
       */
      public traffic.Traffic.TrafficState.State getCurrentState() {
        @SuppressWarnings("deprecation")
        traffic.Traffic.TrafficState.State result = traffic.Traffic.TrafficState.State.valueOf(currentState_);
        return result == null ? traffic.Traffic.TrafficState.State.UNRECOGNIZED : result;
      }
      /**
       * <code>.traffic.TrafficState.State currentState = 2;</code>
       */
      public Builder setCurrentState(traffic.Traffic.TrafficState.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currentState_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.traffic.TrafficState.State currentState = 2;</code>
       */
      public Builder clearCurrentState() {
        
        currentState_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:traffic.TrafficState)
    }

    // @@protoc_insertion_point(class_scope:traffic.TrafficState)
    private static final traffic.Traffic.TrafficState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new traffic.Traffic.TrafficState();
    }

    public static traffic.Traffic.TrafficState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrafficState>
        PARSER = new com.google.protobuf.AbstractParser<TrafficState>() {
      @java.lang.Override
      public TrafficState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrafficState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrafficState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrafficState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public traffic.Traffic.TrafficState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_TrafficCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_TrafficCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_TrafficState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_TrafficState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtraffic.proto\022\007traffic\"\223\001\n\016TrafficComm" +
      "and\022\026\n\016intersectionId\030\001 \001(\t\0220\n\007command\030\002" +
      " \001(\0162\037.traffic.TrafficCommand.Command\"7\n" +
      "\007Command\022\016\n\nTURN_GREEN\020\000\022\014\n\010TURN_RED\020\001\022\016" +
      "\n\nEND_STREAM\020\002\"\203\001\n\014TrafficState\022\026\n\016inter" +
      "sectionId\030\001 \001(\t\0221\n\014currentState\030\002 \001(\0162\033." +
      "traffic.TrafficState.State\"(\n\005State\022\t\n\005G" +
      "REEN\020\000\022\007\n\003RED\020\001\022\013\n\007UNKNOWN\020\0022Z\n\023TrafficL" +
      "ightService\022C\n\rManageTraffic\022\027.traffic.T" +
      "rafficCommand\032\025.traffic.TrafficState(\0010\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_traffic_TrafficCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_traffic_TrafficCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_TrafficCommand_descriptor,
        new java.lang.String[] { "IntersectionId", "Command", });
    internal_static_traffic_TrafficState_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_traffic_TrafficState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_TrafficState_descriptor,
        new java.lang.String[] { "IntersectionId", "CurrentState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
